version: '3.8'

services:
  # Service untuk aplikasi Laravel
  app:
    image: ghcr.io/khoirony/financial-report:latest
    container_name: laravel-app
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=PathPrefix(`/financial`)"
      - "traefik.http.routers.laravel.entrypoints=web,websecure"
      - "traefik.http.routers.laravel.tls=true"
      - "traefik.http.routers.laravel.tls.certresolver=myresolver" # <-- PERHATIKAN BAGIAN INI
      - "traefik.http.middlewares.laravel-stripprefix.stripprefix.prefixes=/financial"
      - "traefik.http.routers.laravel.middlewares=laravel-stripprefix"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

  # Service untuk database
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Rony.12345678
      MYSQL_DATABASE: financial-report
      MYSQL_USER: rony
      MYSQL_PASSWORD: Rony.12345678
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: root_default
    external: true