version: '3.8'

services:
  # Service untuk aplikasi Laravel (tidak berubah)
  app:
    image: ghcr.io/khoirony/financial-report:latest
    container_name: laravel-app
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-secure.rule=Host(`laravel.domain-anda.com`)"
      - "traefik.http.routers.laravel-secure.entrypoints=websecure"
      - "traefik.http.routers.laravel-secure.tls.certresolver=myresolver"
      - "traefik.http.services.laravel-service.loadbalancer.server.port=80"

  # --- TAMBAHKAN SERVICE DATABASE DI BAWAH INI ---
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Rony.12345678
      MYSQL_DATABASE: financial-report
      MYSQL_USER: root
      MYSQL_PASSWORD: Rony.12345678
    volumes:
      - ./mysql-data:/var/lib/mysql  # Ini untuk menyimpan data database secara permanen
    networks:
      - traefik_proxy
    # Port 3306 tidak diekspos ke publik untuk keamanan

networks:
  traefik_proxy:
    name: root_default
    external: true