version: '3.8'

services:
  # Service untuk aplikasi Laravel
  app:
    image: ghcr.io/khoirony/financial-report:latest
    container_name: laravel-app
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`financial.khoirony.fun`)"
      - "traefik.http.routers.laravel.entrypoints=web,websecure"
      - "traefik.http.routers.laravel.tls=true"
      - "traefik.http.routers.laravel.tls.certresolver=mytlschallenge"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

  # Service untuk database
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Rony.12345678
      MYSQL_DATABASE: financial-report
      MYSQL_USER: rony
      MYSQL_PASSWORD: Rony.12345678
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - traefik_proxy
    ports:
      - "3307:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - traefik_proxy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3002:3000"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: root_default
    external: true