name: Build and Deploy Laravel to VPS

on:
  push:
    branches:
      - main # Jalankan workflow setiap ada push ke branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Kode
        uses: actions/checkout@v4

      - name: 2. Login ke GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 3. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Membuat tag image: ghcr.io/username/repo:latest
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: 4. Deploy di VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nama-folder-proyek-anda # Masuk ke direktori proyek di VPS
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin # Login Docker di VPS
            docker compose pull # Tarik image versi terbaru
            docker compose up -d # Jalankan container dengan image baru
            docker compose exec app php artisan migrate --force # Jalankan migrasi di dalam container